### ISSUE TITLE
not easy to read

### ISSUE THREAD

**Issue by mmmatthew** [eawag-rdm/researchdata_archiving_guide#2]
Can you add a link in the readme to the rendered html version of the guide?

**Comment by hvwaldow** [comment]
It's right there my friend:
https://github.com/eawag-rdm/researchdata_archiving_guide/blame/master/README.md#L3

Or do you mean this should go into the source:
http://htmlpreview.github.io/?https://github.com/eawag-rdm/researchdata_archiving_guide/blob/master/eaw_research_data_publishing_guide.html

?

**Comment by mmmatthew** [comment]
Ah, I didn't even think to click the doi... I thought that would just point to some static file somewhere.
